### ISSUE TITLE
Undefined index: msisdn

### ISSUE THREAD

**Issue by webmake** [hipay/hipay-fullservice-sdk-php#27]
Somewhere exists data mismatch (either api either lib), which causes undefined index.
Here is the sample of `requestOrderTransactionInformation` endpoint response
```
{
    "transaction": {
        ....
        "order": {
            ....
            "shippingAddress": {
                "firstname": "",
                "lastname": "",
                "streetAddress": "",
                "locality": "",
                "postalCode": "",
                "country": ""
            },
```
and `PersonalInformationMapper` object source visual:
![image](https://user-images.githubusercontent.com/5016464/30814372-a0bb3a34-a218-11e7-9f39-2204acc8f149.png)

stacktrace:
```
#0 /var/www/application/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/Gateway/Mapper/PersonalInformationMapper.php(51): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/applic...', 51, Array)
#1 /var/www/application/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/Mapper/AbstractMapper.php(74): HiPay\Fullservice\Gateway\Mapper\PersonalInformationMapper->mapResponseToModel()
#2 /var/www/application/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/Gateway/Mapper/OrderMapper.php(58): HiPay\Fullservice\Mapper\AbstractMapper->getModelObjectMapped()
#3 /var/www/application/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/Mapper/AbstractMapper.php(74): HiPay\Fullservice\Gateway\Mapper\OrderMapper->mapResponseToModel()
#4 /var/www/application/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/Gateway/Mapper/TransactionMapper.php(98): HiPay\Fullservice\Mapper\AbstractMapper->getModelObjectMapped()
#5 /var/www/application/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/Mapper/AbstractMapper.php(74): HiPay\Fullservice\Gateway\Mapper\TransactionMapper->mapResponseToModel()
#6 /var/www/application/hipay-fullservice-sdk-php/lib/HiPay/Fullservice/Gateway/Client/GatewayClient.php(253): HiPay\Fullservice\Mapper\AbstractMapper->getModelObjectMapped()
```

**Comment by legithubdeaymeric** [comment]
Hi,
Thanks for bug report.
We are going to fix it quickly.
Could you give me your php version please ?

**Comment by webmake** [comment]
7.1

**Comment by BenoitLeveque** [comment]
@legithubdeaymeric any chance to have a new release with this fix ?

**Comment by jprotin** [comment]
Hi @BenoitLeveque 

A new release will be available thursday.

Many thanks.

**Comment by legithubdeaymeric** [comment]
Hi,
Release 1.6.1

Thanks
